### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Made it easier to make the first pr

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Clears issue #24

**Comment by Yadrishi** [comment]
Hello!
Updating the README.md is not a feature solving in the project.
The readme is already designed by us, also the documentation will be done at the last of the OSoC'23.
Updating the README.md will contain the UI screenshots, brief features of project.

**Comment by karthiknadar1204** [comment]
So no points for the readme file update?

**Comment by Yadrishi** [comment]
No not yet

**Comment by karthiknadar1204** [comment]
@Yadrishi Please reconfirm this, In another project I was told we will be getting points for the readme as well

**Pull request closed without merging**
